# Generated by Django 4.2.6 on 2023-10-24 21:43

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('cover', models.ImageField(upload_to='movies/covers', verbose_name='Обложка')),
                ('teaser', models.CharField(max_length=255, verbose_name='Тизер (YouTube)')),
                ('rating', models.DecimalField(decimal_places=5, max_digits=6, validators=[api.validators.decimal_min_value], verbose_name='Рейтинг')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('genre', models.CharField(max_length=255, verbose_name='Жанр')),
                ('tagline', models.CharField(max_length=255, verbose_name='Слоган')),
                ('director', models.CharField(max_length=255, verbose_name='Режиссер')),
                ('screenwriter', models.CharField(max_length=255, verbose_name='Сценарист')),
                ('producer', models.CharField(max_length=255, verbose_name='Продюсер')),
                ('operator', models.CharField(max_length=255, verbose_name='Оператор')),
                ('composer', models.CharField(max_length=255, verbose_name='Композитор')),
                ('artist', models.CharField(max_length=255, verbose_name='Художник')),
                ('edit', models.CharField(max_length=255, verbose_name='Монтаж')),
                ('fees', models.PositiveIntegerField(verbose_name='Сборы в мире')),
                ('premiere', models.DateField(verbose_name='Премьера в мире')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность (в минутах)')),
                ('actors', models.TextField(verbose_name='Актеры')),
            ],
        ),
    ]
