# Generated by Django 4.2.6 on 2023-10-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_visit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Посещение', 'verbose_name_plural': 'Посещения'},
        ),
    ]
